language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -e .
script:
  - py.test --pep8 --cov keepassx --cov-report term-missing
notifications:
  email:
    - js@jamesls.com
after_success: coveralls
