language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls pytest-cov --use-mirrors
script:
  - py.test --cov keepassx --cov-report term-missing
notifications:
  email:
    - js@jamesls.com
after_success: coveralls
